import { useEffect, useRef } from "react";
import { useTrackingStore, type TrackingSnapshot } from "../../stores/useTrackingStore";
const ORB_STATES=new Set(["orb-forming","orb-stable","orb-compressing","orb-expanding","orb-charging","orb-released","orb-fading"]);
const clamp=(v:number,min=0,max=1)=>Math.min(max,Math.max(min,v));
const ease=(v:number)=>1-Math.pow(1-clamp(v),3);
export const EnergyOrb=()=>{const canvasRef=useRef<HTMLCanvasElement|null>(null);const snapshot=useTrackingStore();const latest=useRef<TrackingSnapshot>(snapshot);latest.current=snapshot;
 useEffect(()=>{const canvas=canvasRef.current;if(!canvas)return;const ctx=canvas.getContext("2d");if(!ctx)return;let raf=0;const particles=Array.from({length:220},(_,i)=>({phase:i*.618,radius:(i%17)/17,band:i%4,speed:.35+(i%9)*.045,size:i%11===0?2:1}));
 const draw=(time:number)=>{const data=latest.current;const rect=canvas.getBoundingClientRect(),dpr=Math.min(devicePixelRatio||1,2);if(canvas.width!==Math.round(rect.width*dpr)||canvas.height!==Math.round(rect.height*dpr)){canvas.width=Math.round(rect.width*dpr);canvas.height=Math.round(rect.height*dpr);}ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,rect.width,rect.height);if(!ORB_STATES.has(data.interactionState)){raf=requestAnimationFrame(draw);return;}
 const anchor=data.twoHandAnchor;const point=data.releaseAnchor??anchor?.smoothedMidpoint??{x:0,y:0,z:0};const x=(point.x+1)*.5*rect.width,y=(1-point.y)*.5*rect.height;const formation=data.interactionState==="orb-forming"?ease(data.formationProgress):1;const release=data.interactionState==="orb-released"?data.releaseProgress:0;const fade=data.interactionState==="orb-fading"?.5:1;const expansion=anchor?.expansionCurve??anchor?.normalizedDistance??.2;const radiusWorld=anchor?.visualRadius??anchor?.targetVisualRadius??.3;const base=Math.max(16,radiusWorld*Math.min(rect.width,rect.height)*.16)*(.3+.7*formation);const sx=anchor?.stretchX??1,sy=anchor?.stretchY??1,angle=anchor?.axisAngle??anchor?.angle??0;const charge=data.charge;const intensity=(.62+charge*2)*formation*(1-release*.4)*fade;ctx.save();ctx.globalCompositeOperation="lighter";
 if(release>0){const shock=base+ease(release)*Math.max(rect.width,rect.height)*.34;ctx.strokeStyle=`rgba(110,225,255,${Math.pow(1-release,1.5)*.8})`;ctx.lineWidth=2+5*(1-release);ctx.beginPath();ctx.arc(x,y,shock,0,Math.PI*2);ctx.stroke();ctx.strokeStyle=`rgba(235,255,255,${Math.pow(1-release,2)*.6})`;ctx.lineWidth=1;ctx.beginPath();ctx.arc(x,y,shock*.82,0,Math.PI*2);ctx.stroke();}
 const glow=ctx.createRadialGradient(x,y,0,x,y,base*3.2);glow.addColorStop(0,`rgba(239,255,255,${.95*intensity})`);glow.addColorStop(.2,`rgba(85,221,255,${.7*intensity})`);glow.addColorStop(.56,`rgba(56,108,255,${.22*intensity})`);glow.addColorStop(1,"rgba(0,0,0,0)");ctx.fillStyle=glow;ctx.beginPath();ctx.arc(x,y,base*3.2,0,Math.PI*2);ctx.fill();
 for(let shell=0;shell<4;shell++){const rr=base*(.55+shell*.28)*(1+expansion*.35+charge*.18+release*1.8);ctx.strokeStyle=`rgba(${shell===0?195:75},${shell===0?252:175},255,${(.46-shell*.08)*intensity*(1-release)})`;ctx.lineWidth=shell===0?1.5:1;ctx.beginPath();ctx.ellipse(x,y,rr*sx,rr*sy,angle+time*.0002*(shell%2?-1:1),0,Math.PI*2);ctx.stroke();}
 for(let i=0;i<2;i++){const ring=base*(1.15+i*.38+expansion*.5+release*1.5);ctx.strokeStyle=`rgba(122,226,255,${(.24-i*.06)*intensity*(1-release)})`;ctx.lineWidth=1;ctx.beginPath();ctx.ellipse(x,y,ring*sx,ring*sy*.64,angle+time*.00035*(i?1:-1),0,Math.PI*2);ctx.stroke();}
 particles.forEach(q=>{const a=q.phase+time*.001*q.speed*(1+charge*4)*(q.band%2?-1:1);const orbit=base*(1.2+q.radius*(1.5+expansion*.8)+q.band*.18)*(1+release*q.radius*5);const px=x+Math.cos(a)*orbit*sx,py=y+Math.sin(a)*orbit*sy;ctx.fillStyle=`rgba(155,235,255,${(.3+q.radius*.42)*intensity*(1-release)})`;ctx.fillRect(px-q.size*.5,py-q.size*.5,q.size,q.size);});
 const core=ctx.createRadialGradient(x-base*.22,y-base*.25,0,x,y,base);core.addColorStop(0,"#ffffff");core.addColorStop(.18,`rgba(187,252,255,${.99*intensity})`);core.addColorStop(.56,`rgba(56,164,255,${.8*intensity})`);core.addColorStop(1,"rgba(31,65,218,0)");ctx.fillStyle=core;ctx.beginPath();ctx.ellipse(x,y,base*(1-release*.3)*sx,base*(1-release*.3)*sy,angle,0,Math.PI*2);ctx.fill();
 if(data.interactionState==="orb-released"&&release<.22){ctx.fillStyle=`rgba(255,255,255,${(1-release/.22)*.7})`;ctx.beginPath();ctx.arc(x,y,base*2.5,0,Math.PI*2);ctx.fill();}ctx.restore();raf=requestAnimationFrame(draw);};raf=requestAnimationFrame(draw);return()=>cancelAnimationFrame(raf);},[]);
 return <canvas ref={canvasRef} className="energy-orb" aria-label="Two-hand energy orb"/>;
};


